'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports DD = DevComponents.DotNetBar

Namespace My
    
    '注意: 此文件是自动生成的；请不要直接修改它。若要进行更改，
    ' 或者如果您在此文件中遇到生成错误，请转至项目设计器
    ' (转至“项目属性”或在解决方案资源管理器中双击“我的项目”节点)，
    ' 然后在“应用程序”选项卡中进行更改。
    '
    Partial Friend Class MyApplication
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined)
            Me.IsSingleInstance = true
            Me.EnableVisualStyles = true
            Me.SaveMySettingsOnExit = true
            Me.ShutDownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()> _
        Protected Overrides Sub OnCreateMainForm()
            AddHandler DD.LocalizationKeys.LocalizeString, AddressOf LocalizationKeys_LocalizeString
            Me.MainForm = Global.DesktopTips.MainForm
        End Sub

        Private Sub LocalizationKeys_LocalizeString(sender As Object, e As DD.LocalizeEventArgs)
            'DD.MessageBoxEx.UseSystemLocalizedString = True

            Select Case e.Key
                ' MessageBox
                Case DD.LocalizationKeys.MessageBoxYesButton
                    e.LocalizedValue = "是"
                    e.Handled = True
                Case DD.LocalizationKeys.MessageBoxNoButton
                    e.LocalizedValue = "否"
                    e.Handled = True
                Case DD.LocalizationKeys.MessageBoxOkButton
                    e.LocalizedValue = "确定"
                    e.Handled = True
                Case DD.LocalizationKeys.MessageBoxCancelButton
                    e.LocalizedValue = "取消"
                    e.Handled = True
                Case DD.LocalizationKeys.MessageBoxHelpButton
                    e.LocalizedValue = "帮助"
                    e.Handled = True
                Case DD.LocalizationKeys.MessageBoxIgnoreButton
                    e.LocalizedValue = "忽略"
                    e.Handled = True
                Case DD.LocalizationKeys.MessageBoxTryAgainButton
                    e.LocalizedValue = "重试"
                    e.Handled = True
                Case DD.LocalizationKeys.MessageBoxRetryButton
                    e.LocalizedValue = "重试"
                    e.Handled = True
                Case DD.LocalizationKeys.MessageBoxContinueButton
                    e.LocalizedValue = "继续"
                    e.Handled = True
                Case DD.LocalizationKeys.MessageBoxCloseButton
                    e.LocalizedValue = "关闭"
                    e.Handled = True
                Case DD.LocalizationKeys.MessageBoxAbortButton
                    e.LocalizedValue = "终止"
                    e.Handled = True

                    ' Color

                Case DD.LocalizationKeys.ColorPickerCaption
                    e.LocalizedValue = "选择颜色"
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerDialogRedLabel
                    e.LocalizedValue = "R："
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerDialogGreenLabel
                    e.LocalizedValue = "G："
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerDialogBlueLabel
                    e.LocalizedValue = "B："
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerMoreColorsMenuItem
                    e.LocalizedValue = "更多颜色(&M)..."
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerStandardColorsLabel
                    e.LocalizedValue = "标准颜色"
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerThemeColorsLabel
                    e.LocalizedValue = "主题颜色"
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerTabStandard
                    e.LocalizedValue = "标准"
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerTabCustom
                    e.LocalizedValue = "自定义"
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerDialogOKButton
                    e.LocalizedValue = "确定"
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerDialogCancelButton
                    e.LocalizedValue = "取消"
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerDialogColorModelLabel
                    e.LocalizedValue = "颜色模型"
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerDialogNewColorLabel
                    e.LocalizedValue = "新"
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerDialogCurrentColorLabel
                    e.LocalizedValue = "当前"
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerDialogCustomColorsLabel
                    e.LocalizedValue = "  颜色："
                    e.Handled = True
                Case DD.LocalizationKeys.ColorPickerDialogStandardColorsLabel
                    e.LocalizedValue = "  颜色："
                    e.Handled = True
            End Select
        End Sub
    End Class

End Namespace
